/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/knative/eventing/contrib/googlecloudpubsub/pkg/apis/messaging/v1alpha1"
	scheme "github.com/knative/eventing/contrib/googlecloudpubsub/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GoogleCloudPubSubChannelsGetter has a method to return a GoogleCloudPubSubChannelInterface.
// A group's client should implement this interface.
type GoogleCloudPubSubChannelsGetter interface {
	GoogleCloudPubSubChannels(namespace string) GoogleCloudPubSubChannelInterface
}

// GoogleCloudPubSubChannelInterface has methods to work with GoogleCloudPubSubChannel resources.
type GoogleCloudPubSubChannelInterface interface {
	Create(*v1alpha1.GoogleCloudPubSubChannel) (*v1alpha1.GoogleCloudPubSubChannel, error)
	Update(*v1alpha1.GoogleCloudPubSubChannel) (*v1alpha1.GoogleCloudPubSubChannel, error)
	UpdateStatus(*v1alpha1.GoogleCloudPubSubChannel) (*v1alpha1.GoogleCloudPubSubChannel, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.GoogleCloudPubSubChannel, error)
	List(opts v1.ListOptions) (*v1alpha1.GoogleCloudPubSubChannelList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GoogleCloudPubSubChannel, err error)
	GoogleCloudPubSubChannelExpansion
}

// googleCloudPubSubChannels implements GoogleCloudPubSubChannelInterface
type googleCloudPubSubChannels struct {
	client rest.Interface
	ns     string
}

// newGoogleCloudPubSubChannels returns a GoogleCloudPubSubChannels
func newGoogleCloudPubSubChannels(c *MessagingV1alpha1Client, namespace string) *googleCloudPubSubChannels {
	return &googleCloudPubSubChannels{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the googleCloudPubSubChannel, and returns the corresponding googleCloudPubSubChannel object, and an error if there is any.
func (c *googleCloudPubSubChannels) Get(name string, options v1.GetOptions) (result *v1alpha1.GoogleCloudPubSubChannel, err error) {
	result = &v1alpha1.GoogleCloudPubSubChannel{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("googlecloudpubsubchannels").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GoogleCloudPubSubChannels that match those selectors.
func (c *googleCloudPubSubChannels) List(opts v1.ListOptions) (result *v1alpha1.GoogleCloudPubSubChannelList, err error) {
	result = &v1alpha1.GoogleCloudPubSubChannelList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("googlecloudpubsubchannels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested googleCloudPubSubChannels.
func (c *googleCloudPubSubChannels) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("googlecloudpubsubchannels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a googleCloudPubSubChannel and creates it.  Returns the server's representation of the googleCloudPubSubChannel, and an error, if there is any.
func (c *googleCloudPubSubChannels) Create(googleCloudPubSubChannel *v1alpha1.GoogleCloudPubSubChannel) (result *v1alpha1.GoogleCloudPubSubChannel, err error) {
	result = &v1alpha1.GoogleCloudPubSubChannel{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("googlecloudpubsubchannels").
		Body(googleCloudPubSubChannel).
		Do().
		Into(result)
	return
}

// Update takes the representation of a googleCloudPubSubChannel and updates it. Returns the server's representation of the googleCloudPubSubChannel, and an error, if there is any.
func (c *googleCloudPubSubChannels) Update(googleCloudPubSubChannel *v1alpha1.GoogleCloudPubSubChannel) (result *v1alpha1.GoogleCloudPubSubChannel, err error) {
	result = &v1alpha1.GoogleCloudPubSubChannel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("googlecloudpubsubchannels").
		Name(googleCloudPubSubChannel.Name).
		Body(googleCloudPubSubChannel).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *googleCloudPubSubChannels) UpdateStatus(googleCloudPubSubChannel *v1alpha1.GoogleCloudPubSubChannel) (result *v1alpha1.GoogleCloudPubSubChannel, err error) {
	result = &v1alpha1.GoogleCloudPubSubChannel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("googlecloudpubsubchannels").
		Name(googleCloudPubSubChannel.Name).
		SubResource("status").
		Body(googleCloudPubSubChannel).
		Do().
		Into(result)
	return
}

// Delete takes name of the googleCloudPubSubChannel and deletes it. Returns an error if one occurs.
func (c *googleCloudPubSubChannels) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("googlecloudpubsubchannels").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *googleCloudPubSubChannels) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("googlecloudpubsubchannels").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched googleCloudPubSubChannel.
func (c *googleCloudPubSubChannels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GoogleCloudPubSubChannel, err error) {
	result = &v1alpha1.GoogleCloudPubSubChannel{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("googlecloudpubsubchannels").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
