/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "knative.dev/eventing/pkg/apis/eventing/v1alpha1"
	scheme "knative.dev/eventing/pkg/client/clientset/versioned/scheme"
)

// SchemaGroupsGetter has a method to return a SchemaGroupInterface.
// A group's client should implement this interface.
type SchemaGroupsGetter interface {
	SchemaGroups(namespace string) SchemaGroupInterface
}

// SchemaGroupInterface has methods to work with SchemaGroup resources.
type SchemaGroupInterface interface {
	Create(*v1alpha1.SchemaGroup) (*v1alpha1.SchemaGroup, error)
	Update(*v1alpha1.SchemaGroup) (*v1alpha1.SchemaGroup, error)
	UpdateStatus(*v1alpha1.SchemaGroup) (*v1alpha1.SchemaGroup, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SchemaGroup, error)
	List(opts v1.ListOptions) (*v1alpha1.SchemaGroupList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SchemaGroup, err error)
	SchemaGroupExpansion
}

// schemaGroups implements SchemaGroupInterface
type schemaGroups struct {
	client rest.Interface
	ns     string
}

// newSchemaGroups returns a SchemaGroups
func newSchemaGroups(c *EventingV1alpha1Client, namespace string) *schemaGroups {
	return &schemaGroups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the schemaGroup, and returns the corresponding schemaGroup object, and an error if there is any.
func (c *schemaGroups) Get(name string, options v1.GetOptions) (result *v1alpha1.SchemaGroup, err error) {
	result = &v1alpha1.SchemaGroup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("schemagroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SchemaGroups that match those selectors.
func (c *schemaGroups) List(opts v1.ListOptions) (result *v1alpha1.SchemaGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SchemaGroupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("schemagroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested schemaGroups.
func (c *schemaGroups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("schemagroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a schemaGroup and creates it.  Returns the server's representation of the schemaGroup, and an error, if there is any.
func (c *schemaGroups) Create(schemaGroup *v1alpha1.SchemaGroup) (result *v1alpha1.SchemaGroup, err error) {
	result = &v1alpha1.SchemaGroup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("schemagroups").
		Body(schemaGroup).
		Do().
		Into(result)
	return
}

// Update takes the representation of a schemaGroup and updates it. Returns the server's representation of the schemaGroup, and an error, if there is any.
func (c *schemaGroups) Update(schemaGroup *v1alpha1.SchemaGroup) (result *v1alpha1.SchemaGroup, err error) {
	result = &v1alpha1.SchemaGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("schemagroups").
		Name(schemaGroup.Name).
		Body(schemaGroup).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *schemaGroups) UpdateStatus(schemaGroup *v1alpha1.SchemaGroup) (result *v1alpha1.SchemaGroup, err error) {
	result = &v1alpha1.SchemaGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("schemagroups").
		Name(schemaGroup.Name).
		SubResource("status").
		Body(schemaGroup).
		Do().
		Into(result)
	return
}

// Delete takes name of the schemaGroup and deletes it. Returns an error if one occurs.
func (c *schemaGroups) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("schemagroups").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *schemaGroups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("schemagroups").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched schemaGroup.
func (c *schemaGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SchemaGroup, err error) {
	result = &v1alpha1.SchemaGroup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("schemagroups").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
