# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-cloud-pubsub-controller
  namespace: knative-eventing
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      messaging.knative.dev/channel: google-cloud-pubsub-channel
      messaging.knative.dev/role: controller
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: google-cloud-pubsub-controller
      containers:
        - name: controller
          image: github.com/knative/eventing/contrib/google_cloud_pubsub/cmd/controller
          env:
            - name: DEFAULT_GCP_PROJECT
              value: REPLACE_WITH_GCP_PROJECT
            - name: DEFAULT_SECRET_NAMESPACE
              value: knative-eventing
            - name: DEFAULT_SECRET_NAME
              value: google-cloud-pubsub-channel-key
            - name: DEFAULT_SECRET_KEY
              value: key.json
            - name: CONFIG_LOGGING_NAME
              value: config-logging
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config-logging
              mountPath: /etc/config-logging
      volumes:
        - name: config-logging
          configMap:
            name: config-logging
