/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "knative.dev/eventing/pkg/apis/eventing/v1alpha1"
)

// FakeSchemaGroups implements SchemaGroupInterface
type FakeSchemaGroups struct {
	Fake *FakeEventingV1alpha1
	ns   string
}

var schemagroupsResource = schema.GroupVersionResource{Group: "eventing.knative.dev", Version: "v1alpha1", Resource: "schemagroups"}

var schemagroupsKind = schema.GroupVersionKind{Group: "eventing.knative.dev", Version: "v1alpha1", Kind: "SchemaGroup"}

// Get takes name of the schemaGroup, and returns the corresponding schemaGroup object, and an error if there is any.
func (c *FakeSchemaGroups) Get(name string, options v1.GetOptions) (result *v1alpha1.SchemaGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(schemagroupsResource, c.ns, name), &v1alpha1.SchemaGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SchemaGroup), err
}

// List takes label and field selectors, and returns the list of SchemaGroups that match those selectors.
func (c *FakeSchemaGroups) List(opts v1.ListOptions) (result *v1alpha1.SchemaGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(schemagroupsResource, schemagroupsKind, c.ns, opts), &v1alpha1.SchemaGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SchemaGroupList{ListMeta: obj.(*v1alpha1.SchemaGroupList).ListMeta}
	for _, item := range obj.(*v1alpha1.SchemaGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested schemaGroups.
func (c *FakeSchemaGroups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(schemagroupsResource, c.ns, opts))

}

// Create takes the representation of a schemaGroup and creates it.  Returns the server's representation of the schemaGroup, and an error, if there is any.
func (c *FakeSchemaGroups) Create(schemaGroup *v1alpha1.SchemaGroup) (result *v1alpha1.SchemaGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(schemagroupsResource, c.ns, schemaGroup), &v1alpha1.SchemaGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SchemaGroup), err
}

// Update takes the representation of a schemaGroup and updates it. Returns the server's representation of the schemaGroup, and an error, if there is any.
func (c *FakeSchemaGroups) Update(schemaGroup *v1alpha1.SchemaGroup) (result *v1alpha1.SchemaGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(schemagroupsResource, c.ns, schemaGroup), &v1alpha1.SchemaGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SchemaGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSchemaGroups) UpdateStatus(schemaGroup *v1alpha1.SchemaGroup) (*v1alpha1.SchemaGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(schemagroupsResource, "status", c.ns, schemaGroup), &v1alpha1.SchemaGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SchemaGroup), err
}

// Delete takes name of the schemaGroup and deletes it. Returns an error if one occurs.
func (c *FakeSchemaGroups) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(schemagroupsResource, c.ns, name), &v1alpha1.SchemaGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSchemaGroups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(schemagroupsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SchemaGroupList{})
	return err
}

// Patch applies the patch and returns the patched schemaGroup.
func (c *FakeSchemaGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SchemaGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(schemagroupsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SchemaGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SchemaGroup), err
}
